apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: marvel-team-builder
  namespace: ibmcd
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: master
    spec:
      containers:
      - name: master
        image: xiago64/marvel:latest
        ports:
        - containerPort: 80